import Head from 'next/head';
import { Box } from '@/components/Box';
import { ColorModeToggle } from '@/components/ColorModeToggle/ColorModeToggle';
import { ContentBlock } from '@/components/ContentBlock/ContentBlock';
import MoreStories from '@/components/MoreStories/MoreStories';
import { Heading } from '@/components/Typography/Heading';
import Layout from '@/components/templates/layout';
import { PostMeta } from '@/interface/post';
import { getAllPosts } from '@/lib/api';

type Props = {
  allPosts: PostMeta[]
}

export default function Index({ allPosts }: Props) {
  const morePosts = allPosts.slice(0)

  return (
    <Layout>
      <Head>
        <title>Forestone log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentBlock
        size={{ mobile: 'standard', desktop: 'xxlarge' }}
        withGutters
      >
        <Box position="relative">
          <Box
            display="flex"
            justifyContent="flex-end"
            paddingBottom={{
              mobile: 'large',
              tablet: 'none',
              desktop: 'xxlarge',
            }}
          >
            <ColorModeToggle />
          </Box>
        </Box>
      </ContentBlock>
      <ContentBlock size="xxlarge">
        <Box
            display="flex"
            justifyContent="center"
            paddingY="xxlarge"
        >
          <Heading level='2'>
            hero area
          </Heading>
        </Box>
      </ContentBlock>
      <ContentBlock size="xxlarge" withGutters>
        {morePosts.length > 0 && <MoreStories posts={morePosts} />}
      </ContentBlock>
    </Layout>
  )
}

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
  ])

  return {
    props: { allPosts },
  }
}
